# Site settings
title: Under Construction Indefinitely
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Daniel Chen.
  Please forgive me while I slowly learn how Jekyll works...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mrdanielchen.com" # the base hostname & protocol for your site
twitter_username: chendaniely
github_username:  chendaniely
photoblog: dan.aminus3.com
wordpress: 69.195.124.76

# Build settings
markdown: kramdown

permalink: /blog/:year/:month/:day/:title

exclude:	   ['*.ipynb']
